### ISSUE TITLE
Support dynamic GCS location for newly collected dataset

### ISSUE THREAD

**Issue by deep-diver** [deep-diver/Continuous-Adaptation-for-Machine-Learning-System-to-Data-Changes#10]
Current behavior
- [97_Prepare_Test_Images Nootebook](https://github.com/deep-diver/Continuous-Adaptation-for-Machine-Learning-System-to-Data-Changes/blob/main/notebooks/97_Prepare_Test_Images.ipynb) collects and uploads new image data to fixed GCS location (i.e. `gs://batch-prediction-collection-3`)
- **Batch Prediction Pipeline**'s `FileListGen` only looks up the fixed GCS location to generate a `FileList`.
- This is problematic because `FileListGen` always use the cached result when `enable_cache=True` (the same input of the GCS location let the pipeline assume to use cached result).

To be updated behavior
- Collected image data from [97_Prepare_Test_Images Nootebook](https://github.com/deep-diver/Continuous-Adaptation-for-Machine-Learning-System-to-Data-Changes/blob/main/notebooks/97_Prepare_Test_Images.ipynb) should be stored in a unique GCS location such as `gs://batch-prediction-collection-3/YYYY-MM` (if we want to store monthly dataset).
- **Batch Prediction Pipeline**'s `FileListGen` should take an GCS location as an input which is a type of `RuntimeParameter`.
- Cloud Function from [04_Cloud_Scheduler_Trigger notebook](https://github.com/deep-diver/Continuous-Adaptation-for-Machine-Learning-System-to-Data-Changes/blob/main/notebooks/04_Cloud_Scheduler_Trigger.ipynb) should calculate the latest GCS location by date, then pass the GCS location to the **Batch Prediction Pipeline** as an RuntimeParameter.

**Comment by deep-diver** [comment]
@sayakpaul 

maybe you can work on to modify `FileListGen`'s fixed input to RuntimeParameter.

**Comment by sayakpaul** [comment]
@deep-diver I think adding a single line of change to the FileListGen might do it:

```py
@component
def FileListGen(
    outpath: OutputArtifact[String],
    project: Parameter[str],
    gcs_source_bucket: Parameter[str],
    gcs_source_prefix: Parameter[str] = data_types.RuntimeParameter(ptype=str),
    output_filename: Parameter[str] = "test-images.txt",
):
    logging.info("FileListGen started")

    client = storage.Client(project=project)
    bucket = client.get_bucket(gcs_source_bucket)
    blobs = bucket.list_blobs(prefix=gcs_source_prefix)
    logging.info("Successfully retrieve the file(jpg) list from GCS path")

    f = open(output_filename, "w")
    for blob in blobs:
        if blob.name.split(".")[-1] == "jpg":
            prefix = ""
            if gcs_source_prefix != "":
                prefix = f"/{gcs_source_prefix}"
            line = f"gs://{gcs_source_bucket}{prefix}/{blob.name}\n"
            f.write(line)
    f.close()
    logging.info(
        f"Successfully created the file list file({output_filename}) in local storage"
    )

    prefix = ""
    if gcs_source_prefix != "":
        prefix = f"{gcs_source_prefix}/"
    blob = bucket.blob(f"{prefix}{output_filename}")
    blob.upload_from_filename(output_filename)
    logging.info(f"Successfully uploaded the file list ({prefix}{output_filename})")

    outpath.value = gcs_source_bucket + "/" + prefix + output_filename
```

And accordingly the `data_gcs_prefix` argument of `_create_pipeline()` method would need to be changed to `data_types.RuntimeParameter`.

But while reading the code to understand some of the components, I realized we will need to incorporate changes to the following components to support this feature:

* `SpanPreparator` (in particular, this line: `image_paths = tf.io.gfile.glob(f"gs://{gcs_source_bucket}/*.jpg")`)
* `PerformanceEvaluator` (in particular, how `latest_directory` is being crafted)

And then we just need to publish the GCS location as a topic to Pub/Sub. I guess this part is yet to be implemented in the notebook or we need to modify this bit:

```
!gcloud scheduler jobs create pubsub $SCHEDULER_JOB_NAME --schedule "*/3 * * * *" --topic $PUBSUB_TOPIC --attributes name=scheduler #every hour
```

Let me know if you would like to run something by me or want me to review anything in this regard.

**Comment by sayakpaul** [comment]
Seems like the current implementation should already take care of that but I wanted to double-check.
