### ISSUE TITLE
Notebook to gather dataset for simulating data drift

### ISSUE THREAD

**Issue by deep-diver** [deep-diver/Continuous-Adaptation-for-Machine-Learning-System-to-Data-Changes#2]
Create a separate notebook to gather data of different distribution from the original CIFAR10 dataset. 

If possible, we can show how those two datasets are different

**Comment by sayakpaul** [comment]
Created this demo notebook: https://gist.github.com/sayakpaul/2164f6c96c0b768185f25cd7150c254e. 

We can build on top of it I guess.

**Comment by deep-diver** [comment]
@sayakpaul 

looks good to me. I have one doubt though.
Is it OK to have images that is too different from the original CIFAR10?
Images downloaded from Bing in this way are very likely to be too different I guess.

**Comment by sayakpaul** [comment]
Yes, good point. What we can do is first downsample them to 32 x 32 and then serialize.

**Comment by deep-diver** [comment]
yeah, maybe we also need to filter manually some of the images (which looks completely not the case)

**Comment by sayakpaul** [comment]
If we specify the classes explicitly then I think this could be circumvented.
