### ISSUE TITLE
`01_Dataset_Prep.ipynb`

### ISSUE THREAD

**Issue by sayakpaul** [deep-diver/Continuous-Adaptation-for-Machine-Learning-System-to-Data-Changes#4]
> When there will be more data with the same distribution, we can update the currently stored dataset. In this case, you should turn on the GCS's versioning feature.

Worth providing a link that shows how to enable the feature mentioned here.

> When there will be more data with the different distribution, we will create other directores of span-2/test and span-2/test to address data drift. In this way, we can keep data separetly for easier maintanence while handling versioning separtely for different SPANs.

Did you mean `span-2/**train**` and span-2/test?

The notebook currently has permission errors. Also,

> Please note this section only works within GCP Vertex Notebook environment due to the authentication issue. If you know how to setup GCS access privilege for TFX, please let me know.

Can't we mitigate this with `from google.colab import auth; auth.authenticate_user()` for a Colab runtime?

Also, could you share the GCS bucket with me?

**Comment by deep-diver** [comment]
@sayakpaul 

thanks for the valuable comment!
First of all, the GCS bucket is public accessible
and the last section works with colab authentication! thanks :)

**Comment by sayakpaul** [comment]
Cool then. Closing the issue.
